### ISSUE TITLE
Full file path or just the exe name?

### ISSUE THREAD

**Issue by wywywywy** [Choum28/AutoHDR#1]
Are we supposed to put in the full file path (e.g. `C:\Users\xxx\AppData\Local\Google\Chrome\Application\chrome.exe`) or just the name of the executable (e.g. `chrome.exe`)?

And does the name matter? Or is it just for identification with no functional use.

**Comment by Choum28** [comment]
You can set the full path or just the executable name, both will work.

If you set the full path\exe Auto-HDR activation will limited to this path\exe only.
In case of Executable name only, autohdr will be activated for all game/app with the same exe

The name is just for identification in the registry and in this script.

**Comment by wywywywy** [comment]
That answers the question. Many thanks.

**Comment by Choum28** [comment]
To be more precise about the Name.

The name in the app is just cosmetic (it will create a registry key with that name to list app).

But the String Value "Name" in the script is where you set the path or exe, it will also be created below the Registry key "Name of the game".

Ex : If you set in the app : 
Name : Outlaws
Exe : f:\Mygame\Outlaws.exe

The script will create : 

Reg key -> HKEY_CURRENT_USER\Software\Microsoft\Direct3D\Outlaws      
String value -> KEY_CURRENT_USER\Software\Microsoft\Direct3D\Outlaws\Name  #value : f:\Mygame\Outlaws.exe
String Value -> HKEY_CURRENT_USER\Software\Microsoft\Direct3D\Outlaws\D3DBehaviors

**Comment by wywywywy** [comment]
Thanks. Worth putting into the README imo
